"""empty message

Revision ID: 146ee029fa5c
Revises: 
Create Date: 2019-02-14 14:40:55.326062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146ee029fa5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('sex', sa.String(length=5), nullable=False),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('imgurl', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('account')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
